### ISSUE TITLE
Download of the ESD failed.

### ISSUE THREAD

**Issue by Localuser0** [mtniehaus/MediaTool#1]
Hey

I get this error: Download of the ESD failed.

![Udklip](https://user-images.githubusercontent.com/125663148/231155730-61f51fc1-aebf-4fff-8433-a8d05df8953e.JPG)

ATP/Defender disabled.

**Comment by mtniehaus** [comment]
Can you try again with the updated zip file here on Github?  I haven't seen that issue with my most recent testing.  The basic challenge is that it appears the MS CDN doesn't have all the images in all locations, so it can fail to download some images from some locations.

**Comment by mtniehaus** [comment]
It's also possible that the download is failing for other reasons, e.g. lack of disk space.  Check the Bits-Client event log to see if any error message was logged.

**Comment by mattbalzan** [comment]
Just add logic in your code to check disk space.

**Comment by mattbalzan** [comment]
Here’s the code:

```
# Define the threshold for free space (5 GB)
$threshold = 5GB

# Get the OS drive (assumed to be the drive with the Windows folder)
$osDrive = (Get-WmiObject Win32_OperatingSystem).SystemDrive

# Get the free space on the OS drive
$freeSpace = (Get-PSDrive -Name $osDrive.TrimEnd(':')).Free

# Check if the free space is greater than or equal to the threshold

if ($freeSpace -ge $threshold) {
    Write-Output "The OS drive ($osDrive) has sufficient free space: $([math]::round($freeSpace/1GB, 2)) GB."
} else {
    Write-Output "Warning: The OS drive ($osDrive) has less than 5 GB of free space. Current free space: $([math]::round($freeSpace/1GB, 2)) GB."
}
```

**Comment by mtniehaus** [comment]
I added logic to check local paths for available free space, and will check before downloading the ESD file whether it will fit.  I didn't check to see if the ISO won't fit, but did add error handling that will show when the ISO creation fails.

You can specify a network path for the download; I didn't add logic to check that location.
