### ISSUE TITLE
Windows Operating System Issue

### ISSUE THREAD

**Issue by kdavis51** [mtniehaus/MediaTool#3]
I see "Windows 20H2" and "WIndows (" in the drop down menu in the tool.   The tool reports back 5300 some images, but looks like the parsing of the xml has gone wonkers.

**Comment by grimson73** [comment]
Same here
<img width="591" alt="image" src="https://github.com/mtniehaus/MediaTool/assets/45716059/1959e15c-3f26-4e5f-9c84-0ef8100ca8f7">

https://oofhours.com/2023/03/29/another-windows-media-creation-tool-sure-why-not/
Latest version on this website is 'oofhoursmediatool-4.zip' but seems equal to this Github version (MediaToolApp.exe)

**Comment by mtniehaus** [comment]
Sorry about that, odd PowerShell bug with unknown versions.  I fixed that and updated everything to know about the latest releases.  Grab the zip file from Github.
