### ISSUE TITLE
ISO not being generated

### ISSUE THREAD

**Issue by philjorgensen** [mtniehaus/MediaTool#4]
Hey Michael,

I've tried downloading the Enterprise and Pro SKUs for ARM64 but doesn't appear to generate the ISO as it remains an .esd. The tool shows it captured it successfully though. Screenshot attached.
 
![Capture](https://github.com/user-attachments/assets/c4a8d035-b0d2-4260-8287-2003e251910a)

**Comment by mtniehaus** [comment]
Odd.  It appears that the OSCDIMG.EXE command didn't run or it failed.  I added some additional logic to (a) check that OSCDIMG.EXE exists at the expected location in the ADK, and (b) that it returned a zero return code.  Can you try that new version (zip from Github) to see if that fixes it?

**Comment by philjorgensen** [comment]
Appears to be fixed! 23H2 ARM64 ISO generated successfully. Thank you!
